type Country = {
	name: string;
	code: string;
	emoji: string;
};
export const COUNTRIES: Country[] = [
	{ name: "Afganistan", code: "AF", emoji: "🇦🇫" },
	{ name: "Almanya", code: "DE", emoji: "🇩🇪" },
	{ name: "Amerika Birleşik Devletleri", code: "US", emoji: "🇺🇸" },
	{ name: "Andorra", code: "AD", emoji: "🇦🇩" },
	{ name: "Angola", code: "AO", emoji: "🇦🇴" },
	{ name: "Antigua ve Barbuda", code: "AG", emoji: "🇦🇬" },
	{ name: "Arjantin", code: "AR", emoji: "🇦🇷" },
	{ name: "Arnavutluk", code: "AL", emoji: "🇦🇱" },
	{ name: "Avustralya", code: "AU", emoji: "🇦🇺" },
	{ name: "Avusturya", code: "AT", emoji: "🇦🇹" },
	{ name: "Azerbaycan", code: "AZ", emoji: "🇦🇿" },
	{ name: "Bahamalar", code: "BS", emoji: "🇧🇸" },
	{ name: "Bahreyn", code: "BH", emoji: "🇧🇭" },
	{ name: "Bangladeş", code: "BD", emoji: "🇧🇩" },
	{ name: "Barbados", code: "BB", emoji: "🇧🇧" },
	{ name: "Belarus", code: "BY", emoji: "🇧🇾" },
	{ name: "Belçika", code: "BE", emoji: "🇧🇪" },
	{ name: "Belize", code: "BZ", emoji: "🇧🇿" },
	{ name: "Benin", code: "BJ", emoji: "🇧🇯" },
	{ name: "Birleşik Arap Emirlikleri", code: "AE", emoji: "🇦🇪" },
	{ name: "Birleşik Krallık", code: "GB", emoji: "🇬🇧" },
	{ name: "Bolivya", code: "BO", emoji: "🇧🇴" },
	{ name: "Bosna Hersek", code: "BA", emoji: "🇧🇦" },
	{ name: "Botsvana", code: "BW", emoji: "🇧🇼" },
	{ name: "Brezilya", code: "BR", emoji: "🇧🇷" },
	{ name: "Brunei", code: "BN", emoji: "🇧🇳" },
	{ name: "Bulgaristan", code: "BG", emoji: "🇧🇬" },
	{ name: "Burkina Faso", code: "BF", emoji: "🇧🇫" },
	{ name: "Burundi", code: "BI", emoji: "🇧🇮" },
	{ name: "Butan", code: "BT", emoji: "🇧🇹" },
	{ name: "Cezayir", code: "DZ", emoji: "🇩🇿" },
	{ name: "Cibuti", code: "DJ", emoji: "🇩🇯" },
	{ name: "Çad", code: "TD", emoji: "🇹🇩" },
	{ name: "Çek Cumhuriyeti", code: "CZ", emoji: "🇨🇿" },
	{ name: "Çin", code: "CN", emoji: "🇨🇳" },
	{ name: "Danimarka", code: "DK", emoji: "🇩🇰" },
	{ name: "Dominik Cumhuriyeti", code: "DO", emoji: "🇩🇴" },
	{ name: "Ekvador", code: "EC", emoji: "🇪🇨" },
	{ name: "Ekvator Ginesi", code: "GQ", emoji: "🇬🇶" },
	{ name: "El Salvador", code: "SV", emoji: "🇸🇻" },
	{ name: "Endonezya", code: "ID", emoji: "🇮🇩" },
	{ name: "Eritre", code: "ER", emoji: "🇪🇷" },
	{ name: "Ermenistan", code: "AM", emoji: "🇦🇲" },
	{ name: "Estonya", code: "EE", emoji: "🇪🇪" },
	{ name: "Etiyopya", code: "ET", emoji: "🇪🇹" },
	{ name: "Fas", code: "MA", emoji: "🇲🇦" },
	{ name: "Fiji", code: "FJ", emoji: "🇫🇯" },
	{ name: "Filipinler", code: "PH", emoji: "🇵🇭" },
	{ name: "Finlandiya", code: "FI", emoji: "🇫🇮" },
	{ name: "Fransa", code: "FR", emoji: "🇫🇷" },
	{ name: "Gabon", code: "GA", emoji: "🇬🇦" },
	{ name: "Gambiya", code: "GM", emoji: "🇬🇲" },
	{ name: "Gana", code: "GH", emoji: "🇬🇭" },
	{ name: "Gine", code: "GN", emoji: "🇬🇳" },
	{ name: "Gine Bissau", code: "GW", emoji: "🇬🇼" },
	{ name: "Grenada", code: "GD", emoji: "🇬🇩" },
	{ name: "Guatemala", code: "GT", emoji: "🇬🇹" },
	{ name: "Guyana", code: "GY", emoji: "🇬🇾" },
	{ name: "Güney Afrika", code: "ZA", emoji: "🇿🇦" },
	{ name: "Güney Kore", code: "KR", emoji: "🇰🇷" },
	{ name: "Güney Sudan", code: "SS", emoji: "🇸🇸" },
	{ name: "Gürcistan", code: "GE", emoji: "🇬🇪" },
	{ name: "Haiti", code: "HT", emoji: "🇭🇹" },
	{ name: "Hırvatistan", code: "HR", emoji: "🇭🇷" },
	{ name: "Hindistan", code: "IN", emoji: "🇮🇳" },
	{ name: "Hollanda", code: "NL", emoji: "🇳🇱" },
	{ name: "Honduras", code: "HN", emoji: "🇭🇳" },
	{ name: "Irak", code: "IQ", emoji: "🇮🇶" },
	{ name: "İran", code: "IR", emoji: "🇮🇷" },
	{ name: "İrlanda", code: "IE", emoji: "🇮🇪" },
	{ name: "İspanya", code: "ES", emoji: "🇪🇸" },
	{ name: "İsrail", code: "IL", emoji: "🇮🇱" },
	{ name: "İsveç", code: "SE", emoji: "🇸🇪" },
	{ name: "İsviçre", code: "CH", emoji: "🇨🇭" },
	{ name: "İtalya", code: "IT", emoji: "🇮🇹" },
	{ name: "İzlanda", code: "IS", emoji: "🇮🇸" },
	{ name: "Jamaika", code: "JM", emoji: "🇯🇲" },
	{ name: "Japonya", code: "JP", emoji: "🇯🇵" },
	{ name: "Kamboçya", code: "KH", emoji: "🇰🇭" },
	{ name: "Kamerun", code: "CM", emoji: "🇨🇲" },
	{ name: "Kanada", code: "CA", emoji: "🇨🇦" },
	{ name: "Karadağ", code: "ME", emoji: "🇲🇪" },
	{ name: "Katar", code: "QA", emoji: "🇶🇦" },
	{ name: "Kazakistan", code: "KZ", emoji: "🇰🇿" },
	{ name: "Kenya", code: "KE", emoji: "🇰🇪" },
	{ name: "Kıbrıs", code: "CY", emoji: "🇨🇾" },
	{ name: "Kırgızistan", code: "KG", emoji: "🇰🇬" },
	{ name: "Kolombiya", code: "CO", emoji: "🇨🇴" },
	{ name: "Komorlar", code: "KM", emoji: "🇰🇲" },
	{ name: "Kongo", code: "CG", emoji: "🇨🇬" },
	{ name: "Kosova", code: "XK", emoji: "🇽🇰" },
	{ name: "Kosta Rika", code: "CR", emoji: "🇨🇷" },
	{ name: "Kuveyt", code: "KW", emoji: "🇰🇼" },
	{ name: "Kuzey Makedonya", code: "MK", emoji: "🇲🇰" },
	{ name: "Küba", code: "CU", emoji: "🇨🇺" },
	{ name: "Laos", code: "LA", emoji: "🇱🇦" },
	{ name: "Lesotho", code: "LS", emoji: "🇱🇸" },
	{ name: "Letonya", code: "LV", emoji: "🇱🇻" },
	{ name: "Liberya", code: "LR", emoji: "🇱🇷" },
	{ name: "Libya", code: "LY", emoji: "🇱🇾" },
	{ name: "Liechtenstein", code: "LI", emoji: "🇱🇮" },
	{ name: "Litvanya", code: "LT", emoji: "🇱🇹" },
	{ name: "Lübnan", code: "LB", emoji: "🇱🇧" },
	{ name: "Lüksemburg", code: "LU", emoji: "🇱🇺" },
	{ name: "Macaristan", code: "HU", emoji: "🇭🇺" },
	{ name: "Madagaskar", code: "MG", emoji: "🇲🇬" },
	{ name: "Malavi", code: "MW", emoji: "🇲🇼" },
	{ name: "Maldivler", code: "MV", emoji: "🇲🇻" },
	{ name: "Malezya", code: "MY", emoji: "🇲🇾" },
	{ name: "Mali", code: "ML", emoji: "🇲🇱" },
	{ name: "Malta", code: "MT", emoji: "🇲🇹" },
	{ name: "Meksika", code: "MX", emoji: "🇲🇽" },
	{ name: "Mısır", code: "EG", emoji: "🇪🇬" },
	{ name: "Moğolistan", code: "MN", emoji: "🇲🇳" },
	{ name: "Moldova", code: "MD", emoji: "🇲🇩" },
	{ name: "Monako", code: "MC", emoji: "🇲🇨" },
	{ name: "Moritanya", code: "MR", emoji: "🇲🇷" },
	{ name: "Mozambik", code: "MZ", emoji: "🇲🇿" },
	{ name: "Myanmar", code: "MM", emoji: "🇲🇲" },
	{ name: "Namibya", code: "NA", emoji: "🇳🇦" },
	{ name: "Nepal", code: "NP", emoji: "🇳🇵" },
	{ name: "Nijer", code: "NE", emoji: "🇳🇪" },
	{ name: "Nijerya", code: "NG", emoji: "🇳🇬" },
	{ name: "Nikaragua", code: "NI", emoji: "🇳🇮" },
	{ name: "Norveç", code: "NO", emoji: "🇳🇴" },
	{ name: "Özbekistan", code: "UZ", emoji: "🇺🇿" },
	{ name: "Pakistan", code: "PK", emoji: "🇵🇰" },
	{ name: "Panama", code: "PA", emoji: "🇵🇦" },
	{ name: "Papua Yeni Gine", code: "PG", emoji: "🇵🇬" },
	{ name: "Paraguay", code: "PY", emoji: "🇵🇾" },
	{ name: "Peru", code: "PE", emoji: "🇵🇪" },
	{ name: "Polonya", code: "PL", emoji: "🇵🇱" },
	{ name: "Portekiz", code: "PT", emoji: "🇵🇹" },
	{ name: "Romanya", code: "RO", emoji: "🇷🇴" },
	{ name: "Ruanda", code: "RW", emoji: "🇷🇼" },
	{ name: "Rusya", code: "RU", emoji: "🇷🇺" },
	{ name: "San Marino", code: "SM", emoji: "🇸🇲" },
	{ name: "Sao Tome ve Principe", code: "ST", emoji: "🇸🇹" },
	{ name: "Senegal", code: "SN", emoji: "🇸🇳" },
	{ name: "Seyşeller", code: "SC", emoji: "🇸🇨" },
	{ name: "Sırbistan", code: "RS", emoji: "🇷🇸" },
	{ name: "Sierra Leone", code: "SL", emoji: "🇸🇱" },
	{ name: "Singapur", code: "SG", emoji: "🇸🇬" },
	{ name: "Slovakya", code: "SK", emoji: "🇸🇰" },
	{ name: "Slovenya", code: "SI", emoji: "🇸🇮" },
	{ name: "Solomon Adaları", code: "SB", emoji: "🇸🇧" },
	{ name: "Somali", code: "SO", emoji: "🇸🇴" },
	{ name: "Sri Lanka", code: "LK", emoji: "🇱🇰" },
	{ name: "Sudan", code: "SD", emoji: "🇸🇩" },
	{ name: "Surinam", code: "SR", emoji: "🇸🇷" },
	{ name: "Suriye", code: "SY", emoji: "🇸🇾" },
	{ name: "Suudi Arabistan", code: "SA", emoji: "🇸🇦" },
	{ name: "Şili", code: "CL", emoji: "🇨🇱" },
	{ name: "Tacikistan", code: "TJ", emoji: "🇹🇯" },
	{ name: "Tanzanya", code: "TZ", emoji: "🇹🇿" },
	{ name: "Tayland", code: "TH", emoji: "🇹🇭" },
	{ name: "Tayvan", code: "TW", emoji: "🇹🇼" },
	{ name: "Togo", code: "TG", emoji: "🇹🇬" },
	{ name: "Trinidad ve Tobago", code: "TT", emoji: "🇹🇹" },
	{ name: "Tunus", code: "TN", emoji: "🇹🇳" },
	{ name: "Türkiye", code: "TR", emoji: "🇹🇷" },
	{ name: "Türkmenistan", code: "TM", emoji: "🇹🇲" },
	{ name: "Uganda", code: "UG", emoji: "🇺🇬" },
	{ name: "Ukrayna", code: "UA", emoji: "🇺🇦" },
	{ name: "Umman", code: "OM", emoji: "🇴🇲" },
	{ name: "Uruguay", code: "UY", emoji: "🇺🇾" },
	{ name: "Ürdün", code: "JO", emoji: "🇯🇴" },
	{ name: "Vanuatu", code: "VU", emoji: "🇻🇺" },
	{ name: "Venezuela", code: "VE", emoji: "🇻🇪" },
	{ name: "Vietnam", code: "VN", emoji: "🇻🇳" },
	{ name: "Yemen", code: "YE", emoji: "🇾🇪" },
	{ name: "Yeni Zelanda", code: "NZ", emoji: "🇳🇿" },
	{ name: "Yeşil Burun", code: "CV", emoji: "🇨🇻" },
	{ name: "Yunanistan", code: "GR", emoji: "🇬🇷" },
	{ name: "Zambiya", code: "ZM", emoji: "🇿🇲" },
	{ name: "Zimbabve", code: "ZW", emoji: "🇿🇼" },
];
